import { ThemeProvider } from "@/providers/ThemeProviders";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

/**
 * Store Root Layout
 * @param children
 * @returns
 */
export default function RootStoreLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <div>{children}</div>;
}
