import { ApolloWrapper } from '@/providers/ApolloProvider'
import StoreProvider from '@providers/StoreProvider'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Store Title',
  description: 'Generated by create next app',
}

/**
 * Store Root Layout
 * @param children
 * @returns
 */
export default async function RootStoreLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: {
    store: string
  }
}) {
  return (
    <ApolloWrapper>
      <StoreProvider store={params.store} messages={{}} settings={{}}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </StoreProvider>
    </ApolloWrapper>
  )
}
